spring.application.name=smart-junk-tracker
# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate ddl auto
spring.jpa.hibernate.ddl-auto=update

# Show SQL in console
spring.jpa.show-sql=true

# H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
